// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feufokxcmlqbgyffqjqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZldWZva3hjbWxxYmd5ZmZxanFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODIyMTgsImV4cCI6MjA2NDE1ODIxOH0.kHAaI6cIZqZEOm8SqkGsNy-iSRsggu9j05CQAIMXvvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);